#! /usr/bin/env bash

function llvm-cov() {
    $(xcode-select -p)/Toolchains/XcodeDefault.xctoolchain/usr/bin/llvm-cov "$@"
}

bin_path="$(swift build --show-bin-path)"
xctest_path="$(find $bin_path -name '*.xctest')"
pkg_name="$(basename $xctest_path .xctest)"

profdata_path="$bin_path/codecov/default.profdata"
pkg_contents_path="$xctest_path/Contents/MacOS/$pkg_name"
ignore_regex="\.build|Tests|\.generated.swift"

mkdir -p .coverage

case "$1" in
    generate-html)
        llvm-cov export \
            -format=lcov \
            -ignore-filename-regex="$ignore_regex"\
            -instr-profile="profdata_path" \
            "$pkg_contents_path" \
            > .coverage/lcov.info

        genhtml .coverage/lcov.info --output-directory .coverage/
        ;;
    generate-json)
        llvm-cov export \
            -format=text \
            -ignore-filename-regex="$ignore_regex"\
            -instr-profile="profdata_path" \
            "$pkg_contents_path" \
            > .coverage/lcov.json
        ;;
    report)
        llvm-cov report \
            -ignore-filename-regex="$ignore_regex"\
            -instr-profile="profdata_path" \
            "$pkg_contents_path" \
        ;;
    instr-profile-path)
        echo "$profdata_path"
        ;;
    *)
        echo 'Unrecognized command'
        exit 1
        ;;
esac
