#! /usr/bin/env bash

function llvm-cov() {
    $(xcode-select -p)/Toolchains/XcodeDefault.xctoolchain/usr/bin/llvm-cov "$@"
}

mkdir -p .build
mkdir -p .coverage

bin_path=".build"

xctest_path="$(find $bin_path -name '*.xctest')"
profdata_path="$(find $bin_path -name '*.profdata')"

contents_path="$xctest_path/Contents/MacOS/$(basename $xctest_path .xctest)"

ignore_regex="\.build|Tests|\.generated.swift|\+Live.swift|\+Mock.swift|Sources/StytchCore/KeychainClient/Migrations"

case "$1" in
    generate-html)
        llvm-cov export \
            -format=lcov \
            -ignore-filename-regex="$ignore_regex" \
            -instr-profile="$profdata_path" \
            "$contents_path" \
            > .coverage/lcov.info

        genhtml .coverage/lcov.info --output-directory .coverage/
        ;;
    generate-json)
        llvm-cov export \
            -format=text \
            -ignore-filename-regex="$ignore_regex" \
            -instr-profile="$profdata_path" \
            "$contents_path" \
            > .coverage/lcov.json
        ;;
    report)
        llvm-cov report \
            -ignore-filename-regex="$ignore_regex" \
            -instr-profile="$profdata_path" \
            "$contents_path" \
        ;;
    instr-profile-path)
        if [ -z "$profdata_path" ]; then
          echo "MISSINGPATH"
        else
          echo "$profdata_path"
        fi
        ;;
    *)
        echo 'Unrecognized command'
        exit 1
        ;;
esac
