name: Lint/Test
on:
  pull_request:
  
jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Bootstrap
      run: |
        make setup
        make bootstrap-tools
    - name: Codegen
      run: |
        make codegen
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        swift test
