name: Lint/Test
on:
  pull_request:
  
jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Mint packages
      uses: actions/cache@v3
      env:
        cache-name: mint-cache
        cache-version: 1
      with:
        path: |
          ~/.mint/
        key: ${{ runner.os }}-${{ env.cache-name }}-build-v${{ env.cache-version }}-${{ hashFiles('Mintfile') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-build-v${{ env.cache-version }}-
          ${{ runner.os }}-${{ env.cache-name }}-build-v
          ${{ runner.os }}-

    - name: Bootstrap
      run: |
        make setup
        make bootstrap-tools

    - name: Codegen
      run: |
        make codegen

    - name: Lint
      run: |
        make lint

    - name: Test
      run: |
        swift test
