name: Lint/Test
on:
  pull_request:
  
jobs:
  test:
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.3.app/Contents/Developer
    runs-on: macos-latest

    steps:
    - run: ls -n /Applications/ | grep Xcode*
    - uses: actions/checkout@v2
    - name: Bootstrap
      run: |
        make setup
        make bootstrap-tools
    - name: Codegen
      run: |
        make codegen
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        swift test
