name: Tom Test

on:
  push:
    branches:
      - 'tomtest'
    
env:
  DEVELOPER_DIR: /Applications/Xcode_14.3.app/Contents/Developer

jobs:
  release:
    runs-on: macos-13

    steps:

    - uses: actions/checkout@v3
      with:
        ref: 0.14.0

    - name: Bootstrap
      uses: ./.github/actions/bootstrap

    - name: List file
      run: aws s3 ls s3://public-assets-stytch-com/sdks/swift/carthage/StytchCore.json
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

